url: "https://mateusai.github.io"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mateu"
      excerpt_separator: "<!--more-->"
      toc: true

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-toc
  - jekyll-feed