defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge